/**
 * Evaluation Dimension (original interface, maintaining compatibility)
 */
export interface EvaluationDimension {
	/** Dimension name */
	name: string;
	/** Dimension weight (0-1) */
	weight: number;
	/** Dimension description */
	description: string;
	/** Evaluation criteria */
	criteria: string[];
	/** Evaluation method */
	evaluationMethod?: string;
	/** Importance description */
	importance?: string;
}

/**
 * Task Analysis Result
 */
export interface TaskAnalysis {
	/** Extracted core task */
	coreTask: string;
	/** Task name for file naming (generated by LLM) */
	taskName: string;
	/** Task type */
	taskType: string;
	/** Task complexity (1-5) */
	complexity: number;
	/** Task domain */
	domain: string;
	/** Key elements */
	keyElements: string[];
	/** Task objectives */
	objectives: string[];
}

/**
 * Time Context Information
 */
export interface TimeContext {
	/** Current timestamp */
	timestamp: number;
	/** Formatted time string */
	formattedTime: string;
	/** Timezone information */
	timezone: string;
	/** Year */
	year: number;
	/** Month */
	month: number;
	/** Day */
	day: number;
	/** Day of week */
	weekday: string;
}

/**
 * Conversation Analysis Input
 */
export interface ConversationInput {
	/** User message */
	userMessage: string;
	/** Conversation history (optional) */
	conversationHistory?: Array<{
		role: 'user' | 'assistant';
		content: string;
		timestamp?: number;
	}>;
	/** Context information (optional) */
	context?: Record<string, unknown>;
}