/**
 * Quality Evaluation Dimension (matches the JSON output format from LLM)
 */
export interface QualityDimension {
	/** Dimension name (3-15 characters, specific and clear) */
	name: string;
	/** One sentence description of what this dimension evaluates */
	description: string;
	/** One sentence explaining why this dimension is critical for the task */
	importance: string;
	/** Scoring criteria for different performance levels */
	scoring: {
		/** Criteria for excellent performance (measurable and actionable) */
		"10": string;
		/** Criteria for good performance (measurable and actionable) */
		"8": string;
		/** Criteria for acceptable performance (measurable and actionable) */
		"6": string;
	};
}

/**
 * Quality Dimensions Response (complete LLM output format)
 */
export interface QualityDimensionsResponse {
	/** Expected score for quality evaluation */
	expectedScore: number;
	/** Score calculation method */
	scoreCalculation: string;
	/** Array of quality evaluation dimensions */
	dimensions: QualityDimension[];
}

/**
 * Task Analysis Result
 */
export interface TaskAnalysis {
	/** Extracted core task */
	coreTask: string;
	/** Task name for file naming (generated by LLM) */
	taskName: string;
	/** Task type */
	taskType: string;
	/** Task complexity (1-5) */
	complexity: number;
	/** Task domain */
	domain: string;
	/** Key elements */
	keyElements: string[];
	/** Task objectives */
	objectives: string[];
}

/**
 * Time Context Information
 */
export interface TimeContext {
	/** Current timestamp */
	timestamp: number;
	/** Formatted time string */
	formattedTime: string;
	/** Timezone information */
	timezone: string;
	/** Year */
	year: number;
	/** Month */
	month: number;
	/** Day */
	day: number;
	/** Day of week */
	weekday: string;
}

/**
 * Conversation Analysis Input
 */
export interface ConversationInput {
	/** User message */
	userMessage: string;
	/** Conversation history (optional) */
	conversationHistory?: Array<{
		role: 'user' | 'assistant';
		content: string;
		timestamp?: number;
	}>;
	/** Context information (optional) */
	context?: Record<string, unknown>;
}